s <- "TCTCCCGATGCTACTACAACAATGTTCATGGATTTACGTGACATCGTTGCCAGAGTAGAA
GATAGGACAGATAGCCGAGGGCAATCGGCACCAGATAGGGTTTCGACCACGACAGTATAG
ATGTGATTTTCTATGATTAACTCAGCGGGGCGTGAGATAAACCGGCATTCGTTTGCTTTT
CTTTTCGTGCAGGCAGACCGGTCGTGTCCTATCACAAATGCTGTGAGGCAGGGAAACCTC
TTGCGTATTCCTCATAGTTCCATGCACTAGAAGGGTATCGGCCCGATCAATAGCAGAGGG
AATAGCAGAATATATGTGAGAATCCACCATTGGGGGTTTGTCACGAACGGACCCACTTGG
TTGTTCCACGCAAAGGACGGACAGGATGTCGCTTGAACTCGAAGTTGCCACCGTATCCCT
ACGGTTAGCGGACTCAGATATAGCGAATTTTACCGGTTAGCCCGCCTCATGTTCACCGCC
CGTGTGCCTCTACCGCTACTGCTCTTGAATTCGAGAACGTCCGCTGGAGCCTATCATTTC
CAACCCACAAGGGATTGCCGTCTGACTAACTGCTAAGCGACAAATGCTCACATGACTCCG
TGAGCAACTCGTGAGTCACGCCACGACACACGCGGGGATTACGATTGTCCGGCTAAACCT
GCCGTCCGTCAGAAACTGTCAACATTGGAAGCGCGATCCTGTATAGAGAGGTCCCCGTGG
GCCTTACTCAACTACGTTGACCGCGACAAATCGAATCTCGGGTCCCTGCCCAAGAAGCCT
AAGGATTGCGGTAAGCCGGAGTTGGGTGGTAGGCAAATGATGAGGAAATGGCCCGATATC
AAAATCAGGCACCCGCCTCTGGCTGGGTGGAGGCCGGGATGGAGTTT"
t <- "TTGCCTACACGT"

s_chars <- strsplit(s, "")[[1]]
t_chars <- strsplit(t, "")[[1]]

indices <- integer(0)
j <- 1  # pointer into t

for (i in seq_along(s_chars)) {
  if (j > length(t_chars)) break
  if (s_chars[i] == t_chars[j]) {
    indices <- c(indices, i)
    j <- j + 1
  }
}

if (j > length(t_chars)) {
  cat(paste(indices, collapse = " "), "\n")
} else {
  cat("No valid subsequence found\n")
}